def gv

pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    environment {
        APP_DIR = 'java-maven-app'
        GIT_REPO_HOST = 'github.com/ronkaiser/devops-08-automation-ci-cd-with-jenkins.git'
        GIT_COMMIT_BRANCH = 'jenkins-jobs'
    }
    stages {
        stage('increment version') {
            steps {
                dir(env.APP_DIR) {
                    script {
                        echo 'incrementing app version...'
                        sh 'mvn build-helper:parse-version versions:set \
                            -DnewVersion=\\\${parsedVersion.majorVersion}.\\\${parsedVersion.minorVersion}.\\\${parsedVersion.nextIncrementalVersion} \
                            versions:commit'
                        def matcher = readFile('pom.xml') =~ '<version>(.+)</version>'
                        def version = matcher[0][1]
                        env.IMAGE_NAME = "$version-$BUILD_NUMBER"
                    }
                }
            }
        }
        stage('build app') {
            steps {
                dir(env.APP_DIR) {
                    script {
                        echo 'building the application...'
                        sh 'mvn clean package'
                    }
                }
            }
        }
        stage('build image') {
            steps {
                dir(env.APP_DIR) {
                    script {
                        echo "building the docker image..."
                        withCredentials([usernamePassword(credentialsId: 'docker-hub-repo', passwordVariable: 'PASS', usernameVariable: 'USER')]){
                            sh "docker build -t ronkaiser86/demo-app:${IMAGE_NAME} ."
                            sh 'echo $PASS | docker login -u $USER --password-stdin'
                            sh "docker push ronkaiser86/demo-app:${IMAGE_NAME}"
                        }
                    }
                }
            }
        }
        stage('deploy') {
            steps {
                dir(env.APP_DIR) {
                    script {
                        echo 'deploying docker image...'
                    }
                }
            }
        }
        stage('commit version update') {
            steps {
                dir(env.APP_DIR) {
                    script {
                        withCredentials([usernamePassword(
                            credentialsId: 'github-credentials',
                            usernameVariable: 'GIT_USERNAME',
                            passwordVariable: 'GIT_PASSWORD'
                        )]) {
                            env.ENCODED_GIT_USERNAME = GIT_USERNAME.replace('@', '%40')
                            sh '''
                                git config user.email "jenkins@example.com"
                                git config user.name "jenkins"
                                git add pom.xml
                                git diff --staged --quiet && exit 0
                                git commit -m "ci: version bump"
                                git push "https://$ENCODED_GIT_USERNAME:$GIT_PASSWORD@$GIT_REPO_HOST" HEAD:$GIT_COMMIT_BRANCH
                            '''
                        }
                    }
                }
            }
        }
    }
}
