def gv

pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    environment {
        APP_DIR = 'java-maven-app'
    }
    stages {
        stage('increment version') {
            steps {
                dir(env.APP_DIR) {
                    script {
                        echo 'incrementing app version...'
                        sh 'mvn build-helper:parse-version versions:set \
                            -DnewVersion=\\\${parsedVersion.majorVersion}.\\\${parsedVersion.minorVersion}.\\\${parsedVersion.nextIncrementalVersion} \
                            versions:commit'
                        def matcher = readFile('pom.xml') =~ '<version>(.+)</version>'
                        def version = matcher[0][1]
                        env.IMAGE_NAME = "$version-$BUILD_NUMBER"
                    }
                }
            }
        }
        stage('build app') {
            steps {
                dir(env.APP_DIR) {
                    script {
                        echo 'building the application...'
                        sh 'mvn clean package'
                    }
                }
            }
        }
        stage('build image') {
            steps {
                dir(env.APP_DIR) {
                    script {
                        echo "building the docker image..."
                        withCredentials([usernamePassword(credentialsId: 'docker-hub-repo', passwordVariable: 'PASS', usernameVariable: 'USER')]){
                            sh "docker build -t ronkaiser86/demo-app:${IMAGE_NAME} ."
                            sh 'echo $PASS | docker login -u $USER --password-stdin'
                            sh "docker push ronkaiser86/demo-app:${IMAGE_NAME}"
                        }
                    }
                }
            }
        }
        stage('deploy') {
            steps {
                dir(env.APP_DIR) {
                    script {
                        echo 'deploying docker image...'
                    }
                }
            }
        }
        stage('commit version update') {
            steps {
                dir(env.APP_DIR) {
                    script {
                        withCredentials([usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                            sh 'git config --global user.email "jenkins@example.com"'
                            sh 'git config --global user.name "jenkins"'

                            sh 'git checkout -B jenkins-jobs'
                            sh 'git status'
                            sh 'git branch'

                            sh 'git remote set-url origin https://github.com/ronkaiser/devops-08-automation-ci-cd-with-jenkins.git'
                            sh 'git add pom.xml'
                            sh 'git commit -m "ci: version bump"'

                            def encodedPass = java.net.URLEncoder.encode(env.PASS, 'UTF-8')
                            sh "git push https://${env.USER}:${encodedPass}@github.com/ronkaiser/devops-08-automation-ci-cd-with-jenkins.git HEAD:jenkins-jobs"
                        }
                    }
                }
            }
        }
    }
}