#!/user/bin/env groovy
@Library('jenkins-shared-libary')
def gv

pipeline {   
    agent any
    tools {
        maven 'maven-3.9'
    }
    environment {
        APP_DIR = 'java-maven-app'
    }
    stages {
        stage("init") {
            steps {
                script {
                    gv = load "./java-maven-app/script.groovy"
                }
            }
        }
        stage("build jar") {
            steps {
                dir(env.APP_DIR) {
                    script {
                        buildJar()
                    }
                }
            }
        }

        stage("build and push image") {
            steps {
                dir(env.APP_DIR) {
                    script {
                        buildImage 'ronkaiser86/demo-app:jma-3.0'
                        dockerLogin()
                        dockerPush 'ronkaiser86/demo-app:jma-3.0'
                    }
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    gv.deployApp()
                }
            }
        }               
    }
} 
